- name: Configure VXLAN
  hosts: junos-2,junos-3
  gather_facts: no
  vars_files:
  - vars/main.yml
  tasks:
  - name: Configure VXLAN
    junipernetworks.junos.junos_config:
      src: "templates/vxlan.j2"
      check_commit: yes
      #confirm_commit: yes
      comment: VXLAN config

  - name: Configure VXLAN commit
    junipernetworks.junos.junos_config:
      backup: yes
      confirm_commit: yes
      comment: VXLAN config commit

  - name: Show VLAN, Interface, PIM
    junipernetworks.junos.junos_command:
      commands:
      - show vlans
      - show interfaces
      #- show protocols pim
    register: result
  - name: VLAN, Interface, PIM
    debug:
      var: result

  - name: Show Ethernet
    junipernetworks.junos.junos_command:
      commands:
      - show ethernet-switching vxlan-tunnel-end-point source
      - show ethernet-switching table
      #- show interface vtep.12345 detail
      - show ospf neighbor
    register: result
  - name: Debug Ethernet
    debug:
      var: result