- name: Configure VXLAN
  hosts: junos-2,junos-3
  gather_facts: no
  vars_files:
  - vars/main.yml
  tasks:
  - name: Configure VXLAN
    junipernetworks.junos.junos_config:
      src: "templates/vxlan.j2"
      confirm_commit: yes
      update: merge
      comment: VXLAN config
