- name: Configure VXLAN
  hosts: junos-1
  gather_facts: no
  vars_files:
  - vars/main.yml
  tasks:
  - name: Show VLAN, Interface, PIM
    junipernetworks.junos.junos_command:
      commands:
      - show vlans
      - show interfaces
      #- show protocols pim
    register: result
  - name: VLAN, Interface, PIM
    debug:
      var: result

  - name: Show Ethernet
    junipernetworks.junos.junos_command:
      commands:
      - show ethernet-switching vxlan-tunnel-end-point source
      - show ethernet-switching table
      #- show interface vtep.12345 detail
      - show ospf neighbor
    register: result
  - name: Debug Ethernet
    debug:
      var: result

  - name: Gather facts
    junipernetworks.junos.junos_facts:
      gather_subset: all
      #gather_subset: config
      #gather_network_resources: all
    register: result
  - name: Debug Ethernet
    debug:
      var: result

  - name: Show config (set)
    junipernetworks.junos.junos_command:
      commands:
      - show configuration | display set | match interface
    register: result
  - name: Debug Configurations
    debug:
      var: result

  - name: Show config (json)
    junipernetworks.junos.junos_command:
      commands:
      - show configuration | display json
    register: result
  - name: Debug Configurations
    debug:
      var: result
